name: Code Format Check
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Run dotnet format
        run: dotnet format --verify-no-changes
